sap.ui.define([
	"sap/ui/base/Object"
], function (Object) {
	"use strict";

	return Object.extend("my.sample.app.service.ExportService", {
		/**
		 * Exports data to PDF format
		 * @param {Object} oData - Data to export
		 * @returns {Promise} Export result
		 */
		exportToPDF: function (oData) {
			return new Promise(function (resolve, reject) {
				// Load jsPDF library dynamically
				sap.ui.require(["https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min"], function () {
					try {
						var sFileName = "Analytics_Report_" + new Date().toISOString().split("T")[0] + ".pdf";
						var sHtml = this._generatePDFContent(oData);
						
						var oElement = document.createElement("div");
						oElement.innerHTML = sHtml;
						
						var oOptions = {
							margin: 10,
							filename: sFileName,
							image: { type: "jpeg", quality: 0.98 },
							html2canvas: { scale: 2 },
							jsPDF: { orientation: "portrait", unit: "mm", format: "a4" }
						};
						
						// For now, we'll use a simpler approach with SAPUI5 built-in Export
						this._generatePDFUsingUIExport(oData).then(resolve).catch(reject);
					} catch (e) {
						reject(e);
					}
				}.bind(this));
			}.bind(this));
		},

		/**
		 * Alternative PDF export using SAPUI5 Export API
		 */
		_generatePDFUsingUIExport: function (oData) {
			return new Promise(function (resolve, reject) {
				try {
					var sContent = this._generatePDFContent(oData);
					var oBlob = new Blob([sContent], { type: "text/html" });
					var sUrl = URL.createObjectURL(oBlob);
					var oLink = document.createElement("a");
					oLink.href = sUrl;
					oLink.download = "Analytics_Report_" + new Date().toISOString().split("T")[0] + ".pdf";
					document.body.appendChild(oLink);
					oLink.click();
					document.body.removeChild(oLink);
					URL.revokeObjectURL(sUrl);
					resolve();
				} catch (e) {
					reject(e);
				}
			}.bind(this));
		},

		/**
		 * Generates HTML content for PDF export
		 */
		_generatePDFContent: function (oData) {
			var sHtml = '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>';
			sHtml += 'body { font-family: Arial, sans-serif; margin: 20px; }';
			sHtml += 'h1 { color: #0066CC; border-bottom: 2px solid #0066CC; padding-bottom: 10px; }';
			sHtml += 'h2 { color: #333; margin-top: 20px; border-left: 4px solid #0066CC; padding-left: 10px; }';
			sHtml += 'table { width: 100%; border-collapse: collapse; margin: 10px 0; }';
			sHtml += 'th { background-color: #0066CC; color: white; padding: 10px; text-align: left; }';
			sHtml += 'td { border: 1px solid #ddd; padding: 10px; }';
			sHtml += 'tr:nth-child(even) { background-color: #f9f9f9; }';
			sHtml += '.kpi { display: inline-block; margin: 10px 20px; }';
			sHtml += '.kpi-value { font-size: 24px; font-weight: bold; color: #0066CC; }';
			sHtml += '.footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }';
			sHtml += '</style></head><body>';

			sHtml += '<h1>' + (oData.title || "Analytics Report") + '</h1>';
			sHtml += '<p><strong>Generated on:</strong> ' + (oData.date || new Date().toLocaleDateString()) + '</p>';

			// KPIs Section
			if (oData.kpis) {
				sHtml += '<h2>Key Performance Indicators</h2>';
				for (var key in oData.kpis) {
					sHtml += '<div class="kpi"><strong>' + key + ':</strong> <span class="kpi-value">' + oData.kpis[key] + '</span></div>';
				}
			}

			// Data Sections
			if (oData.sections && oData.sections.length > 0) {
				oData.sections.forEach(function (section) {
					sHtml += '<h2>' + section.title + '</h2>';
					if (Array.isArray(section.data) && section.data.length > 0) {
						sHtml += this._generateTableHTML(section.data);
					}
				}.bind(this));
			}

			// Departments Table
			if (oData.departments && oData.departments.length > 0) {
				sHtml += '<h2>Department Details</h2>';
				sHtml += '<table>';
				sHtml += '<tr><th>Department</th><th>Employees</th><th>Manager</th><th>Budget</th></tr>';
				oData.departments.forEach(function (dept) {
					sHtml += '<tr><td>' + dept.name + '</td><td>' + dept.employees + '</td><td>' + dept.managerName + '</td><td>' + dept.budget + '</td></tr>';
				});
				sHtml += '</table>';
			}

			sHtml += '<div class="footer"><p>This report was automatically generated by the Analytics & Reports module.</p></div>';
			sHtml += '</body></html>';
			return sHtml;
		},

		/**
		 * Generates HTML table from data array
		 */
		_generateTableHTML: function (aData) {
			if (!aData || aData.length === 0) return "";
			
			var sHtml = '<table>';
			var oFirstRow = aData[0];
			
			// Header row
			sHtml += '<tr>';
			for (var key in oFirstRow) {
				sHtml += '<th>' + key + '</th>';
			}
			sHtml += '</tr>';
			
			// Data rows
			aData.forEach(function (row) {
				sHtml += '<tr>';
				for (var key in row) {
					sHtml += '<td>' + row[key] + '</td>';
				}
				sHtml += '</tr>';
			});
			
			sHtml += '</table>';
			return sHtml;
		},

		/**
		 * Exports data as CSV
		 */
		exportToCSV: function (aData, sFileName) {
			return new Promise(function (resolve, reject) {
				try {
					var sCsv = this._generateCSV(aData);
					var oBlob = new Blob([sCsv], { type: "text/csv;charset=utf-8;" });
					var sUrl = URL.createObjectURL(oBlob);
					var oLink = document.createElement("a");
					oLink.href = sUrl;
					oLink.download = sFileName || "export_" + new Date().toISOString().split("T")[0] + ".csv";
					document.body.appendChild(oLink);
					oLink.click();
					document.body.removeChild(oLink);
					URL.revokeObjectURL(sUrl);
					resolve();
				} catch (e) {
					reject(e);
				}
			}.bind(this));
		},

		/**
		 * Generates CSV content
		 */
		_generateCSV: function (aData) {
			if (!aData || aData.length === 0) return "";
			
			var sCsv = "";
			var oFirstRow = aData[0];
			
			// Header row
			sCsv += Object.keys(oFirstRow).join(",") + "\n";
			
			// Data rows
			aData.forEach(function (row) {
				var aValues = [];
				for (var key in row) {
					aValues.push('"' + (row[key] || "").toString().replace(/"/g, '""') + '"');
				}
				sCsv += aValues.join(",") + "\n";
			});
			
			return sCsv;
		}
	});
});
